[tool.poetry]
name = "pythonproject51"
version = "0.1.0"
description = ""
authors = ["Aidana <a19071997@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
